### ISSUE TITLE
Add `Cluster#id` to be the key 

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_appkit#14]
This would make it easier to work with in Rails too.

So `Cluster#title` is "Ruby" but `Cluster#id` is `ruby`, the key used in the yaml and correspondingly used in the hash.

**Comment by ericfranz** [comment]
Otherwise, if I have a single instance of `Cluster`, I can't use it to determine the key in the "hash" of clusters to "find it" in the future (i.e. build a link to it, for example).

**Comment by ericfranz** [comment]
In a few cases this should make the code a little cleaner, but we probably can get around this as long as we iterate over the hash instead of an array. So this isn't urgent.

**Comment by nickjer** [comment]
Why do you need to find the cluster again if you already have the cluster object?

**Comment by nickjer** [comment]
Although I do need to update the `ShellUrl` to accept a cluster object.

**Comment by nickjer** [comment]
This is fixed as we now use `ClusterDecorator` objects.
