### ISSUE TITLE
OodAppkit.dashboard should return an empty object if dashboard url is not configured.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood_appkit#23]
Our suggested method of obtaining the OodAppkit dashboard URI is to call `OodAppkit.dashboard.url.to_s`

`OodAppkit.dashboard` currently returns `nil` if it is not configured, and so calling `.url` will raise a NoMethodError exception.

An app probably shouldn't crash if the dashboard is not configured, may be more appropriate to set url to `"#"` or empty string on calls to an unconfigured `OodAppkit.dashboard.uri`

**Comment by ericfranz** [comment]
I use `"#"` with the default `PathRouter` that I inject into `OodApp`, so `"#"` is the right solution.

**Comment by nickjer** [comment]
Are you sure it returns `nil`? The code sets default values if not defined...

https://github.com/OSC/ood_appkit/blob/84b3decd948b347928ee0563141a8eccf543fb61/lib/ood_appkit/configuration.rb#L89-L92

**Comment by nickjer** [comment]
Re-open if this is still an issue. But it seems to be fixed already.
