### ISSUE TITLE
Add URL helper for the new download URI

### ISSUE THREAD

**Issue by nickjer** [OSC/ood_appkit#27]
PUNs now come with the new download URI:

```
/pun/download/<path/to/file>
```

This should be treated very similarly for what we do with `OodAppkit::Url::Files` w/o the API.

**Comment by ericfranz** [comment]
Do we need this now that Rails send_file handles this for us? Ah - perhaps for views displaying links to results files. Would this be a replacement for https://github.com/OSC/ood_appkit#rack-middleware-for-handling-files-under-dataroot?

Note: once switching to this, results files will no longer be available if it is not deployed under OOD instance. This might trip people up with tests or doing things via command line. But it probably isn't a big deal.

**Comment by nickjer** [comment]
I am now leaning against this. I believe we should leverage the Rails supplied `send_file` method. We can control whether the disposition is `inline` or `attachment`.
